OurProject/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    
    path('', views.homepage_view, name='home_page'),
    path('admin/', admin.site.urls),
    path('registration/', include('registration.urls')),
]

registration/urls.py
from django.urls import path
from . import views
app_name = "registration" 

urlpatterns = [
       path('api/register/', views.register_user, name='register_user'),
       path('api/users/', views.list_users, name='list_users'),  # new endpoint
       path('api/users/<int:pk>/', views.user_detail, name='user_detail'),
       
       path('login/', views.login_view, name='login_html'),
       path('logout/', views.logout_view, name='logout_html'),
       path('users/', views.users_html, name='users_html'),

]

OurProject/views.py
from django.shortcuts import render

def homepage_view(request):
    return render(request, 'homepage.html')

OurProject/templates/homepage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Homepage — User Registration</title>
    <style>
      body {
        font-family: Arial;
        background: #f7f9fc;
        text-align: center;
        padding: 50px;
      }
      .btn {
        padding: 12px 20px;
        background: #a30000;
        color: white;
        border-radius: 8px;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <h1>Welcome to the User Registration Demo!</h1>
    <p></p>
    <a href="{%url 'registration:login_html'%}" class="btn">Go to Login</a>
  </body>
</html>